TRABALHO PRATICO MODULO  02 




In [5]:
import numpy as np
import pandas as pd 

In [6]:
# == código 1 == # 
Z = np.zeros((4, ))
print("Z:", Z)

Z: [0. 0. 0. 0.]


In [7]:
# == código 2 == #
Z = np.zeros((4, ))
Z[1] = 1. 
print("Z:", Z)

Z: [0. 1. 0. 0.]


In [8]:
# == código 3 == #
Z = np.zeros((4, ))
Z[1: ] = 1.
print("Z:", Z)

Z: [0. 1. 1. 1.]


In [57]:
# == código 4 == #
Z = np.zeros(( 4,  ))
Z[:3] = 1.
print("Z:", Z)

#Z: [1. 1. 1. 0.]

Z: [1. 1. 1. 0.]


In [85]:
# == código 5 == #
X = np.array([[2., 2.], [2.,2.]]) 
print("X:\n", X)

#X:
 #[[2. 2.]
 #[2. 2.]]

X:
 [[2. 2.]
 [2. 2.]]


In [14]:
# == código 6 == #
X = np.array([[1, 2], [3, 4]])
Y = X[0, :]
Y[1] = 10 
print("X:\n", X)

X:
 [[ 1 10]
 [ 3  4]]


In [65]:
# == código 7 == #
X = np.array([[1, 3], [11, 10]])
print(np.mean(X[X > np.pi]))

10.5


In [171]:
# == código 8 == #
data = {'animal' : ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan,  7, 3],
        'visits' : [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': [ 'yes',  'yes',  'no',  'yes', 'no', 'no', 'no',  'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
print(data['animal'])
print(data['age'])
print(data['visits'])
print(data['priority'])

print(labels)
#df.describe()
pd.DataFrame(data=data, index=labels)

['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog']
[2.5, 3, 0.5, nan, 5, 2, 4.5, nan, 7, 3]
[1, 3, 2, 3, 2, 3, 1, 1, 2, 1]
['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [169]:
# == código 9 == #
df = pd.DataFrame(data=data, index=labels)
print(pd.DataFrame)
df.describe()
#df.iloc[:, 3]
#df.loc[:, 'visits']

#df.sort_values(by='visits', ascending=False)
#df.shape
df['animal'].value_counts()

<class 'pandas.core.frame.DataFrame'>


dog      4
cat      4
snake    2
Name: animal, dtype: int64

In [131]:
# == código 10 == #
y_true = np.array([1., 2., 1.])
y_pred = np.array([1.1, 1.98, 1.05])

yy_true_pred = y_pred + y_true
print(y_true, y_pred)
print(yy_true_pred)
np.sqrt(((y_true-y_pred)**2).mean())


[1. 2. 1.] [1.1  1.98 1.05]
[2.1  3.98 2.05]


0.06557438524302006